---
language: c++
dist: jammy
os:
  linux
compiler:
  - gcc
addons:
  apt:
    packages:
      - cmake
      - ninja-build
script:
  - git submodule update
  - cmake --preset gcc-release-ninja
  - cd build/gcc-release-ninja
  - ninja
  - ctest -V
  - sudo cpack .
