---
language: c++
dist: jammy
os:
  linux
compiler:
  - gcc
addons:
  apt:
    packages:
      - cmake
      - ninja-build
  snaps:
    - name: cmake
      confinement: classic
      channel: 3.18/candidate
script:
  - cmake --preset gcc-release-ninja
  - cd build/gcc-release-ninja
  - ninja
  - ctest -V
  - sudo cpack .
