---
language: c++
dist: bionic
os:
  linux
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - cmake
      - ninja-build
script:
  - echo $(pwd)
  - ls -al
  - mkdir build
  - cmake --help
  - cd build
  - CC="${CC}" CXX="${CXX}" cmake .. -G Ninja
  - ninja -C build
